# Waypoints for multiple drones
# Each element in the list corresponds to a drone's waypoint mission.
# Waypoints are defined as [x, y, z] coordinates in ENU (East, North, Up).

drone_waypoints:
  - # Waypoints for Drone 1 (vehicle_id='1'): Letter 'M'
    - [0.0, 0.0, 10.0]
    - [0.1, 10.0, 10.0]
    - [5.0, 5.0, 10.0]
    - [9.9, 10.0, 10.0]
    - [10.0, 0.0, 10.0]
    # Reverse path
    - [9.9, 10.0, 10.0]
    - [5.0, 5.0, 10.0]
    - [0.1, 10.0, 10.0]
    - [0.0, 0.0, 10.0]

  - # Waypoints for Drone 2 (vehicle_id='2'): Letter 'A'
    - [12.0, 0.0, 15.0]
    - [15.0, 10.0, 15.0]
    - [18.0, 0.0, 15.0]
    - [16.5, 5.0, 15.0]
    - [13.5, 5.0, 15.0]
    # Reverse path
    - [12.0, 0.0, 15.0]

  - # Waypoints for Drone 3 (vehicle_id='3'): Letter 'G'
    - [30.0, 0.0, 10.0]
    - [30.0, 5.0, 10.0]
    - [25.0, 5.0, 10.0]
    - [30.0, 5.0, 10.0]
    - [30.0, 0.0, 10.0]
    - [20.0, 0.0, 10.0]
    - [20.0, 10.0, 10.0]
    - [30.0, 10.0, 10.0]
    # Reverse path
    - [20.0, 10.0, 10.0]
    - [20.0, 0.0, 10.0]
    - [30.0, 0.0, 10.0]

  - # Waypoints for Drone 4 (vehicle_id='4'): Letter 'I'
    - [30.0, 0.0, 15.0]
    - [40.0, 0.0, 15.0]
    - [35.0, 0.0, 15.0]
    - [35.0, 10.0, 15.0]
    - [30.0, 10.0, 15.0]
    - [40.0, 10.0, 15.0]
    # Reverse path
    - [30.0, 10.0, 15.0]
    - [35.0, 10.0, 15.0]
    - [35.0, 0.0, 15.0]
    - [30.0, 0.0, 15.0]

  - # Waypoints for Drone 5 (vehicle_id='5'): Letter 'C'
    - [49.0, 0.0, 10.0]
    - [41.0, 0.0, 10.0]
    - [41.0, 10.0, 10.0]
    - [49.0, 10.0, 10.0]
    # Reverse path
    - [41.0, 10.0, 10.0]
    - [41.0, 0.0, 10.0]
    - [49.0, 0.0, 10.0]

  - # Waypoints for Drone 6 (vehicle_id='6'): Letter 'C'
    - [59.0, 0.0, 15.0]
    - [51.0, 0.0, 15.0]
    - [51.0, 10.0, 15.0]
    - [59.0, 10.0, 15.0]
    # Reverse path
    - [51.0, 10.0, 15.0]
    - [51.0, 0.0, 15.0]
    - [59.0, 0.0, 15.0]